[project]
name = "weather-backend"
version = "0.1.0"
description = "Weather API Backend using FastAPI"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.116.1",
    "python-multipart>=0.0.20",
    "uvicorn[standard]>=0.35.0",
]

[project.scripts]
dev = "uvicorn main:app --reload --host 0.0.0.0 --port 3000"
start = "uvicorn main:app --host 0.0.0.0 --port 3000"

[tool.uv]
dev-dependencies = []
